networks:
  default:
    external:
     name: roboshop

services:
  mongodb:
    image: mongodb:1.0


  catalogue:
    image: catalogue:1.0
    depends_on:
    - mongodb

  web:
    image: web:1.0
    ports:
      - "80:80"
    depends_on: 
    - catalogue
